#!/bin/sh
set -x
wget -O chef-server-core_12.3.0-1_amd64.deb https://packagecloud.io/chef/stable/packages/ubuntu/trusty/chef-server-core_12.3.0-1_amd64.deb/download
## Install chef server core
dpkg -i chef-server-core_12.3.0-1_amd64.deb
rm -rf chef-server-core_12.3.0-1_amd64.deb
sysctl -w kernel.shmall=4194304
sysctl -w kernel.shmmax=17179869184
/opt/opscode/embedded/bin/runsvdir-start &
dpkg-divert --local --rename --add /sbin/initctl
ln -sf /bin/true /sbin/initctl
## Configure chef server
chef-server-ctl reconfigure
## Setup administrator user
chef-server-ctl user-create "$USER" "$FNAME" "$LNAME" "$EMAIL" "$PASSWORD" --filename /etc/chef/"$USER".pem
## Setup org + add user to admin (--association_user)
chef-server-ctl org-create "$SORGNAME" "$LORGNAME" --association_user "$USER" --filename /etc/chef/"$USER"_validation.pem
/opt/opscode/embedded/bin/runsvdir-start &
chef-server-ctl reconfigure
## Install Chef WebUI
chef-server-ctl install opscode-manage
opscode-manage-ctl reconfigure
chef-server-ctl reconfigure
tail -F /opt/opscode/embedded/service/*/log/current
